; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{489B6A2F-4DCE-4FB3-90DA-7911665C94A9}}
AppName=NanoVNA-UTN-Toolkit
AppVersion=1.0
;AppVerName=NanoVNA-UTN-Toolkit 1.0
AppPublisher=Proyecto Final 2026, Inc.
AppPublisherURL=http://www.NanoVNA-UTN-Toolkit.com/
AppSupportURL=http://www.NanoVNA-UTN-Toolkit.com/
AppUpdatesURL=http://www.NanoVNA-UTN-Toolkit.com/
DefaultDirName={pf}\NanoVNA-UTN-Toolkit
DisableProgramGroupPage=yes
OutputBaseFilename=NanoVNA-UTN-Toolkit_installer
SetupIconFile=NanoVNA-UTN-Toolkit/icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Executable principal
Source: "NanoVNA-UTN-Toolkit/dist\NanoVNA-UTN-Toolkit\NanoVNA-UTN-Toolkit.exe"; DestDir: "{app}"; Flags: ignoreversion
; Carpeta _internal (libs, datos bundled, INIs default, presets default, JSONs, imagenes)
Source: "NanoVNA-UTN-Toolkit/dist\NanoVNA-UTN-Toolkit\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\NanoVNA-UTN-Toolkit"; Filename: "{app}\NanoVNA-UTN-Toolkit.exe"
Name: "{commondesktop}\NanoVNA-UTN-Toolkit"; Filename: "{app}\NanoVNA-UTN-Toolkit.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\NanoVNA-UTN-Toolkit.exe"; Description: "{cm:LaunchProgram,NanoVNA-UTN-Toolkit}"; Flags: nowait postinstall skipifsilent